### PR TITLE
Fix: Selection should be in the first cell of an inserted table.

### LINKED ISSUE #61: Selection should be in the first cell of an inserted table
Right now it stays outside:

jun-18-2018 12-19-40

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Selection should be in the first cell of an inserted table. Closes #61.

---

### Additional information

* Simple fix - I've made `TableUtils#createTable()` return inserted table element so `InsertTableCommand` can set the selection. I don't think that `TableUtils#createTable()` method should set the selection.

### CODE REVIEW

File: src/tableutils.js [hunk 1]
```diff
@@ -74,17 +74,22 @@ export default class TableUtils extends Plugin {
...
 	 * @param {Number} rows Number of rows to create.
 	 * @param {Number} columns Number of columns to create.
+	 * @returns {module:engine/model/element~Element} Created table element.
 	 */
 	createTable( position, rows, columns ) {
 		const model = this.editor.model;
 
+		let table;
+
 		model.change( writer => {
```
Comment (Reinmar) [inline src/tableutils.js]: You can return table directly from `model.change()`. It fwds its callback's return value.

File: src/commands/inserttablecommand.js [hunk 2]
```diff
@@ -53,7 +53,11 @@ export default class InsertTableCommand extends Command {
 		const isRoot = firstPosition.parent === firstPosition.root;
 		const insertPosition = isRoot ? Position.createAt( firstPosition ) : Position.createAfter( firstPosition.parent );
 
-		tableUtils.createTable( insertPosition, rows, columns );
+		model.change( writer => {
```
Comment (Reinmar) [inline src/commands/inserttablecommand.js]: I miss a test for an integration with undo – if you'd use `model.change()` to wrap `writer.setSelection()`, then  (I think) you'd create two undo steps. Or at least – the created undo step might've been incorrect.

Comment (Reinmar) [reply src/commands/inserttablecommand.js]: Try to write an integration test that undo is clear. If this test won't verify that `model.change()` needs to wrap both calls, then make it a unit test and check that a single batch was created.

**Comment by Reinmar** [comment]
Minor R-.
