### PR TITLE
T/126: Make table block-quotable

### LINKED ISSUE #126: Blockquote applies changes to all cells while table is selected
## Steps to reproduce
1. Create a new table.
1. Select it.
1. Apply a blockquote.

## Current result
The blockquote is inside all cells. I believe it should be applied to the whole table. 

## GIF
bug_cke5

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Make table a block element in the schema for quoting. Closes #126.

---

### Additional information

* Required changes in BlockQuote: https://github.com/ckeditor/ckeditor5-block-quote/pull/27
* Required changes in engine: https://github.com/ckeditor/ckeditor5-engine/pull/1614
* all repos updated for review in main repo: https://github.com/ckeditor/ckeditor5/tree/t/ckeditor5-table/126.

### CODE REVIEW

File: src/tableediting.js [hunk 1]
```diff
@@ -57,7 +57,8 @@ export default class TableEditing extends Plugin {
 			allowWhere: '$block',
 			allowAttributes: [ 'headingRows', 'headingColumns' ],
 			isLimit: true,
-			isObject: true
+			isObject: true,
+			isBlock: true
```
Comment (Reinmar) [inline src/tableediting.js]: Haha, interesting that it was missing for so long.

**Comment by jodator** [comment]
@Reinmar I've added the tests.

**Comment by jodator** [comment]
@scofalik done with moving the `.getTopMostBlocks()` method to the engine.
