### PR TITLE
Table rows will not be added on tab key press if the associated command is disabled

### LINKED ISSUE #185: Adding a row on tab key should use a command
At the moment, if <kbd>Tab</kbd> key is pressed in the last cell of the table a new table row is created and the caret is moved there. This is "hardcoded" - doesn't use `insertTableRowBelow` command. This is incorrect as the command (and all other commands) might be disabled if the table is not editable for some reason (for example, comments-only mode). It will also be better for integration with track changes.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Table rows will not be added on tab key press if the associated command is disabled. Closes #185.

### CODE REVIEW

File: tests/tableediting.js [hunk 1]
```diff
@@ -294,6 +294,22 @@ describe( 'TableEditing', () => {
 				] ) );
 			} );
 
+			it( 'should not create another row and not move the caret if insertTableRowBelow command is disabled', () => {
+				setModelData( model, modelTable( [
+					[ '11', '[12]' ]
```
Comment (jodator) [inline tests/tableediting.js]: maybe test should include also testing the selection so it should start with collapsed and should stay collapsed (not changed) after the <kbd>tab</kbd>.

Comment (jodator) [inline tests/tableediting.js]: maybe test should include also testing the selection so it should start with collapsed and should stay collapsed (not changed) after the <kbd>tab</kbd>.

File: src/tableediting.js [hunk 2]
```diff
@@ -214,16 +214,25 @@ export default class TableEditing extends Plugin {
...
 
 			const isLastCellInRow = currentCellIndex === tableRow.childCount - 1;
-			const isLastRow = currentRowIndex === table.childCount - 1;
+			let isLastRow = currentRowIndex === table.childCount - 1;
 
 			if ( isForward && isLastRow && isLastCellInRow ) {
-				editor.plugins.get( 'TableUtils' ).insertRows( table, { at: table.childCount } );
+				editor.execute( 'insertTableRowBelow' );
+
+				// Re-evaluate `isLastRow`. If `insertTableRowBelow` execution didn't add any row (because it was disabled or it got
```
Comment (jodator) [inline src/tableediting.js]: Too complex? Maybe check if the command is enabled - if not just return.

File: src/tableediting.js [hunk 3]
```diff
@@ -214,16 +214,25 @@ export default class TableEditing extends Plugin {
...
+				// overwritten in some way) this will still be `true`. But if the row was added it will change to `false`.
+				isLastRow = currentRowIndex === table.childCount - 1;
 			}
 
 			let cellToFocus;
 
 			// Move to first cell in next row.
 			if ( isForward && isLastCellInRow ) {
+				if ( isLastRow ) {
```
Comment (jodator) [inline src/tableediting.js]: I don't like the `if` in `if` here. I'd move that check as `if( !command.isEnabled ) { return }` to the previous check of inserting table row.

File: src/tableediting.js (hunk 2 above)
Comment (jodator) [reply src/tableediting.js]: I am not sure what is the case for "got it overwritten in some way" part so maybe I'm wrong here.

But still if the number of rows didn't change I'd exit here rather then in focus condition below.

Comment (scofalik) [reply src/tableediting.js]: That was my first idea, but I wanted to check the content state which is the ultimate source of truth and the indicator of what to do next.

By "got overwritten" I mean that commands behavior (execution) may be overwritten by other features. The command might be enabled but for some reason, it might not add a row. Track changes overwrites commands a lot and some of them do not change the content after execution. I am not yet sure how integration with tables will look like (now you can only add a table but table utils are not supported). So I think I am on a safe side here with the way I coded it.

File: tests/tableediting.js (hunk 1 above)
Comment (scofalik) [reply tests/tableediting.js]: I copied this from the test above. I can change it to a collapsed selection.

File: src/tableediting.js (hunk 2 above)
Comment (jodator) [reply src/tableediting.js]: So the part about earlier abort still applies - just return here not below. (number of rows remains the same). WDYT?

Comment (scofalik) [reply src/tableediting.js]: But I agree that this is confusing.
