### PR TITLE
Fix: Merge cell horizontally should not be possible on overlapped cells.

### LINKED ISSUE #68: Merge cell right should not be possible on overlapped cells
The command should be disabled here:

selection_036

As it produces wrong layout:

selection_037

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Merge cell horizontally should not be possible on overlapped cells. Closes #68.

---

### CODE REVIEW

File: tests/commands/mergecellcommand.js [hunk 1]
```diff
@@ -18,60 +18,62 @@ import {
...
 
 	beforeEach( () => {
-		return ModelTestEditor.create()
-			.then( newEditor => {
-				editor = newEditor;
-				model = editor.model;
-				root = model.document.getRoot( 'main' );
+		return ModelTestEditor.create( {
+			plugins: [ TableUtils ]
+		} ).then( newEditor => {
```
Comment (Reinmar) [inline tests/commands/mergecellcommand.js]:
```js
return ModelTestEditor
    .create( 
        // ...
    )
    .then( 
    );

**Comment by Reinmar** [comment]
I checked all crazy cases like:

image

or:

image


So I feel pretty confident about this change. Good job!
