### PR TITLE
Skip text nodes between `tr` elements during table upcast

### LINKED ISSUE #145: Plugin crashes with spaces in HTML-Code with tables
Hi,

we figured out the following issue with the table plugin:

```js
editor.setData('<table><tbody><tr><td>First row</td></tr><tr><td>Second row</td></tr><tr><td>Third row</td></tr> <tr><td>Fourth row</td></tr></tbody></table>')
```
This causes the following error (reproducable with current master build on ckeditor.com):
```
Uncaught TypeError: t.getChildren is not a function
    at Cg (upcasttable.js:223)
    at upcasttable.js:194
    at Ia.t.on (upcasttable.js:31)
    at Ia.fire (emittermixin.js:196)
    at Ia._convertItem (upcastdispatcher.js:212)
    at Ia._convertChildren (upcastdispatcher.js:243)
    at Ia.La.upcastDispatcher.on (upcast-converters.js:584)
    at Ia.fire (emittermixin.js:196)
    at Ia._convertItem (upcastdispatcher.js:216)
    at Ia.convert (upcastdispatcher.js:171)
```

If we remove the space between the third and fourth-row tr-tag, all works fine.

Can someone of you investigate here?

Thanks!

### PR DESCRIPTION
**Pull request by f1ames**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Skip text nodes between `tr` elements during table upcast. Closes #145.

---

### Additional information

See #145.

### CODE REVIEW

File: src/converters/upcasttable.js [hunk 1]
```diff
@@ -180,7 +180,13 @@ function scanTable( viewTable ) {
 				firstTheadElement = tableChild;
 			}
 
-			for ( const tr of Array.from( tableChild.getChildren() ) ) {
+			// There might be some extra empty text nodes between the `tr`s.
+			// Make sure further code operates on `tr`s only. (#145)
+			const trs = Array.from( tableChild.getChildren() ).filter( el => {
+				return el.is( 'element', 'tr' );
```
Comment (jodator) [inline src/converters/upcasttable.js]: I'd move that to one line - it's simple enough.
